c_stdlib_version:  # [unix]
  - 2.28  # [linux]
  - 11.3  # [osx and x86_64]
build_c_stdlib:
  - sysroot  # [linux]
docker_image:
  - quay.io/condaforge/linux-anvil-alma-x86_64:8  # [linux and x86_64]

c_compiler:
  - clang  # [win]
c_compiler_version:
  - 18  # [win]
cxx_compiler:
  - clangxx  # [win]
cxx_compiler_version:
  - 18  # [win]
