c_stdlib_version:  # [unix]
  - 2.28  # [linux]
  - 11.3  # [osx and x86_64]
build_c_stdlib:
  - sysroot  # [linux]
docker_image:
  - quay.io/condaforge/linux-anvil-alma-x86_64:8  # [linux and x86_64]

m2w64_c_compiler:            # [win and x86_64]
  - gcc                      # [win and x86_64]
m2w64_c_compiler_version:    # [win and x86_64]
  - '13'                     # [win and x86_64]
m2w64_c_stdlib:              # [win and x86_64]
  - m2w64-sysroot            # [win and x86_64]
m2w64_c_stdlib_version:      # [win and x86_64]
  - '12'                     # [win and x86_64]
m2w64_cxx_compiler:          # [win and x86_64]
  - gxx                      # [win and x86_64]
m2w64_cxx_compiler_version:  # [win and x86_64]
  - '13'                     # [win and x86_64]

clang_c_compiler:            # [win and x86_64]
  - clang                    # [win and x86_64]
clang_c_compiler_version:    # [win and x86_64]
  - 18                       # [win and x86_64]
clang_cxx_compiler:          # [win and x86_64]
  - clangxx                  # [win and x86_64]
clang_cxx_compiler_version:  # [win and x86_64]
  - 18                       # [win and x86_64]
clang_c_stdlib:              # [win and x86_64]
  - vs                       # [win and x86_64]
clang_c_stdlib_version:      # [win and x86_64]
  - 2019                     # [win and x86_64]

c_compiler:                  # [win and x86_64]
  - clang                    # [win and x86_64]
c_compiler_version:          # [win and x86_64]
  - 18                       # [win and x86_64]
cxx_compiler:                # [win and x86_64]
  - clangxx                  # [win and x86_64]
cxx_compiler_version:        # [win and x86_64]
  - 18                       # [win and x86_64]
c_stdlib:                    # [win and x86_64]
  - vs                       # [win and x86_64]
c_stdlib_version:            # [win and x86_64]
  - "2019"                   # [win and x86_64]
